defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Dustin Morris
<br>
subtitle: ePortfolio
<br>
subtitle: CS-499 Computer Science Capstone

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Dustin Morris"

# Side Menu Links
menu:
  - text: Professional Self-Assessment
    link: /
    icon: ""

  - text: Code Review
    link: /code-review
    icon: ""

  - text: Artifact 1
    link: /contact
    icon: ""

  - text: Artifact 2
    link: /resume
    icon: ""

  - text: Artifact 3
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/
    icon: fab fa-twitter


    
